crud for book
wolox-training/sd-java pull request #4
Opened 2020-01-09 19:56 UTC by sebasdeldi

**Description**
- Adds CRUD for book

**Card**
- https://trello.com/c/JA2uj5XP/18-crear-las-operaciones-crud-de-book

2020-01-10 02:43 UTC, leandrocostawolox requested changes
Great! Good work with that ControllerAdvice :) 
I asked for some minor changes

2020-01-10 02:43 UTC, leandrocostawolox commented on src/main/java/com/wolox/training/repositories/BookRepository.java
> +  List findByTitle(String title);
You can return Optional in both of these methods :) Something like `Optional<Book>` and `Optional<List<Book>>` To know more about optionals you can read [this link](https://www.baeldung.com/java-optional). This way you can avoid null checks in the rest of your code when you call these methods
It's not part of the training yet but it's very useful

Besides that it's a good practice to return a List of the actual data type you will be using (I mean `List<Book>` instead of just `List`)

2020-01-10 02:43 UTC, leandrocostawolox commented on src/main/java/com/wolox/training/controllers/BookController.java
> +  @GetMapping("/title/{bookTitle}")
Usually it's more restful to use queryparams for this kind of searchs, something like 
`https://localhost:8080/api/books?title=mititulo`
Here you have a [link](https://www.baeldung.com/spring-request-param#a-simple-mapping) that shows how to use them

2020-01-10 20:50 UTC, leandrocostawolox requested changes

2020-01-10 20:50 UTC, leandrocostawolox commented on src/main/java/com/wolox/training/controllers/BookController.java
> +    return bookRepository.findByTitle(title);
Nice! But now that you are using Optional, here you could do something like:

```
return bookRepository.findByTitle(title)
   .orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND,
                "Book with title " + title + " not found"));
```

And this findByTitle method will be returning a List<Book> without that Optional wrapper

2020-01-10 22:08 UTC, Gianni-Nicolas approved these changes
Great job!!!

2020-01-13 15:28 UTC, leandrocostawolox approved these changes
Niiice! :)

2020-01-14 14:17 UTC, merged